//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerOrderStock_11.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashRegister
    {
        public int CashRegisterId { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
